"""restaurant suggestions

Revision ID: 7b1c80da8a41
Revises: 0ef83e2ef866
Create Date: 2026-07-29 06:41:44.651525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '7b1c80da8a41'
down_revision: Union[str, None] = '0ef83e2ef866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='suggestion_status', create_type=False), nullable=False),
    sa.Column('moderator_comment', sa.Text(), nullable=True),
    sa.Column('created_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_restaurant_id'], ['restaurants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('rating_events', sa.Column('restaurant_suggestion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating_events', 'restaurant_suggestions', ['restaurant_suggestion_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating_events', type_='foreignkey')
    op.drop_column('rating_events', 'restaurant_suggestion_id')
    op.drop_table('restaurant_suggestions')
    # ### end Alembic commands ###
