"""trust and rating

Revision ID: 0ef83e2ef866
Revises: b7e91d3c40a2
Create Date: 2026-07-28 17:50:56.927486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ef83e2ef866'
down_revision: Union[str, None] = 'b7e91d3c40a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_status_states',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('promotion_item_id', sa.Integer(), nullable=False),
    sa.Column('stable', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['promotion_item_id'], ['promotion_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id', 'promotion_item_id')
    )
    op.create_table('rating_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['promotion_suggestions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rating_events_city_created', 'rating_events', ['city', 'created_at'], unique=False)
    op.create_index('ix_rating_events_user_created', 'rating_events', ['user_id', 'created_at'], unique=False)
    op.create_table('report_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.Enum('confirmed', 'refuted', 'neutral', name='verdict_outcome'), nullable=False),
    sa.Column('is_pioneer', sa.Boolean(), nullable=False),
    sa.Column('confirmed_items', sa.Integer(), nullable=False),
    sa.Column('refuted_items', sa.Integer(), nullable=False),
    sa.Column('neutral_items', sa.Integer(), nullable=False),
    sa.Column('matured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index('ix_report_verdicts_user_id', 'report_verdicts', ['user_id'], unique=False)
    sa.Enum('on_site', 'delivery', name='report_channel').create(op.get_bind(), checkfirst=True)
    op.add_column('reports', sa.Column('channel', sa.Enum('on_site', 'delivery', name='report_channel', create_type=False), server_default='on_site', nullable=False))
    op.add_column('users', sa.Column('weight', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('users', sa.Column('weight_drifted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_drifted_at')
    op.drop_column('users', 'weight')
    op.drop_column('reports', 'channel')
    op.drop_index('ix_report_verdicts_user_id', table_name='report_verdicts')
    op.drop_table('report_verdicts')
    op.drop_index('ix_rating_events_user_created', table_name='rating_events')
    op.drop_index('ix_rating_events_city_created', table_name='rating_events')
    op.drop_table('rating_events')
    op.drop_table('item_status_states')
    sa.Enum(name='report_channel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='verdict_outcome').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
