"""phone verification codes

Revision ID: 655c65f23748
Revises: fd884716af34
Create Date: 2026-07-29 10:07:32.972399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '655c65f23748'
down_revision: Union[str, None] = 'fd884716af34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_phone_verifications_phone', 'phone_verifications', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_verifications_phone', table_name='phone_verifications')
    op.drop_table('phone_verifications')
    # ### end Alembic commands ###
